application/urls.py
from django.urls import path
from .views import *

app_name = 'application'

urlpatterns = [
    
    # path('', StudentJobApplicationView.as_view(), name='student-job-application'),
    # path("student-job-application-table", StudentJobApplicationTableView.as_view(), name="get-student-job-application-table"),
    # path("delete/student-job-application/<int:id>", DeleteStudentJobApplication.as_view(), name="delete-student-application"),
    # path('employer-for-staff', EmployerJobApplicationStaffView.as_view(), name='employer-for-staff'),
    # path('employer-table-for-staff', EmployerJobApplicationStaffTableView.as_view(), name='get-employer-for-staff-table'),
    # path("student-application-details", StudentApplicationDetailView.as_view(), name="student-application-details"),
    # path("employer-application-details", EmployerApplicationDetailView.as_view(), name="employer-application-details"), 
    # path("admin-job-application-table/<int:index>", AdminJobApplicationTableView.as_view(), name="get-admin-job-application-table"),
    # path('admin', AdminJobApplicationView.as_view(), name='admin-job-application'),


    # path('employer', EmployerJobApplicationView.as_view(), name='employer-job-application'),
    # path("employer-job-application-table", EmployerJobApplicationTableView.as_view(), name="get-employer-job-application-table"),
    # path('employer-delete/<int:id>', DeleteEmployerJobApplication.as_view(), name='employer-job-application-delete'),
 ]

employers/urls.py
from django.urls import path
from .views import *

app_name = 'employers'

urlpatterns = [
    path('', EmployerJobApplicationView.as_view(), name='employer-job-application'),
    path("job-application-table", EmployerJobApplicationTableView.as_view(), name="get-job-application-table"),
    path('<int:id>/delete', DeleteEmployerJobApplication.as_view(), name='employer-job-application-delete'),
    path("employer-application-status-change/<int:id>", ChangeEmployerApplicationStatus.as_view(), name="employer-application-status-change"),
]

inernship/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('community/', include('community.urls')),
    path('application/', include('application.urls')),
    path('events/', include('events.urls')), 
    path('students/', include('students.urls')), 
    path('employers/', include('employers.urls')), 
    path('staffs/', include('staffs.urls')), 
    path('notifcation/', include('notifications.urls')), 
    path('jobs/', include('jobs.urls')), 
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
from django.urls import path
from .views import *

app_name = 'job'

urlpatterns = [ 
    path('',JobListView.as_view(),name="index")
 ]

application/models.py
from calendar import c
from django.db import models

from accounts.models import User, UserProfile

job_title = (
    (1, 'Software Developer'),
    (2, 'Hardware'),
    (3, 'Web Developer'),
    (4, 'Graphics'),
)

status = (
    (1, 'Received'),#recevied for placement
    (2, 'Awaiting Placement'),#recevied for placement
    (3, 'Placed'), #Completed for placement
)


job_type = (
    (1, 'Full-time'),
    (2, 'Part-time'), 
    (3, 'Internship'), 
)
related_fields = (
    ('computer science','computer science'),
    ('information technology','information Technology'), 
    ('networking','Networking'),
    ('fashion','Fashion'),
    ('hardware','Hardware'),
    ('graphic design','Graphic Design'),
    ('graph','Graphic Design'),
)
  
class BaseApplication(models.Model):
    related_field =  models.CharField(max_length=255,choices=related_fields )
    job_type =  models.IntegerField(choices=job_type,null=True)
    highest_qualification = models.CharField(max_length=250, null=True, blank=True)
    yrs_of_experience = models.IntegerField(default=0,null=True, blank=True)
    status = models.IntegerField(choices=status, null=True, blank=True)
    payment_budget = models.CharField(max_length=255,null=True,blank=True)
    location=  models.CharField(max_length=255, null=True, blank=True)
    desciption = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_btn_color(self):
        if self.status ==1:
            return 'btn-info'
        elif self.status ==2:
            return 'btn-success'
        elif self.status ==3:
            return 'btn-success'
    class Meta:
        abstract = True
    


class EmployerApplication(BaseApplication):
    user = models.ForeignKey(UserProfile, related_name="user_em_application", on_delete=models.CASCADE, null=True)
    title= models.CharField(max_length=255, blank=False, null=True)

    class Meta:
        db_table = 'employer_application'
        ordering = ['-created_at']
    
    def owner(self):
        return f"{self.title}"

    def __str__(self):
        return self.owner()

class JobApplication(BaseApplication):
    user = models.ForeignKey(UserProfile, related_name="user_job_application", on_delete=models.CASCADE, null=True)
    cv = models.FileField(upload_to='cv/')

    class Meta:
        db_table = 'job_application'
        ordering = ['-created_at']

    def owner(self):
        return f"{self.user}" 

    def __str__(self):
        return self.owner()

application/forms.py
from django.forms import ModelForm
from application.models import EmployerApplication, JobApplication

class StudentJobApplicationForm(ModelForm): 
    class Meta:
        model = JobApplication
        fields = ['related_field', 'job_type', 'highest_qualification', 'yrs_of_experience', 'status', 'payment_budget', 'location','desciption','cv']

class EmployerJobApplicationForm(ModelForm): 
    class Meta:
        model = EmployerApplication
        fields = ['title', 'related_field', 'job_type', 'yrs_of_experience', 'status', 'location','desciption', 'highest_qualification','location']

application/views.py
 
# from django.http import HttpResponse, JsonResponse
# from django.shortcuts import redirect, render
# from django.views import View
# from accounts.models import UserProfile 
# from notifications.utilities import create_notification
# from application.forms import *
# from django.template import loader
# from application.models import JobApplication
# from django.contrib.auth.mixins import LoginRequiredMixin

# # creating new job application

# # class StudentJobApplicationView(LoginRequiredMixin,View):
# #     login_url = "account:login"
# #     redirect_field_name = "redirect_to"
# #     form_class = StudentJobApplicationForm
# #     template_name = 'accounts/main/application/students/index.html'
    
# #     def get(self,request):
# #         profile = UserProfile.objects.get(user=request.user.id) 
# #         context = {
# #             "title":"Applications",
# #             "profile":profile ,
# #             'form':self.form_class
# #             }
# #         return render(request, self.template_name, context)
 
# #     def post(self,request): 
# #         form = self.form_class(request.POST, request.FILES)
# #         if form.is_valid():
# #             form.instance.user_id=request.user.id
# #             form.instance.status=1 
# #             content = f"An application has been received from { request.user.email }"
# #             create_notification(request=request, notification_type=3, content=content)
# #             form.save()
# #             message = "success"
# #             return JsonResponse({"message":message})
# #         else:
# #             message = "success"
# #             return JsonResponse({"message":message}) 
     
# # class StudentJobApplicationTableView(LoginRequiredMixin,View):
    
# #     login_url = "accounts:login"
# #     redirect_field_name = "redirect_to"

# #     def get(self, request,  *args, **kwargs):
# #         template = loader.get_template("accounts/main/application/students/table.html") 
# #         student_job_applications = JobApplication.objects.filter(user=request.user.id)
# #         profile = UserProfile.objects.get(user_id=request.user.id) 
# #         context = { 
# #             'student_job_applications': student_job_applications,
# #             "profile":profile ,
# #         }
# #         return HttpResponse(template.render(context, self.request))

# # class DeleteStudentJobApplication(LoginRequiredMixin, View):
# #     login_url = "account:login"
# #     redirect_field_name = "redirect_to"
 
# #     def get(self, request, id, *args, **kwargs): 
# #         JobApplication.objects.get(id=id).delete()
# #         message = "success"
# #         return JsonResponse({"message": message })

# # class ChangeStudentApplicationStatus(LoginRequiredMixin,View):
# #     login_url = "account:login"
# #     redirect_field_name = "redirect_to"
# #     def get(self, request, id):
# #     #     is_ajax = request.headers.get("X-Requested-With") == "XMLHttpRequest"
# #     #     if is_ajax:
# #         application = JobApplication.objects.get(id=id)
# #         if application.status == 4:
# #             application.status = 3
# #             content = "Your application has been successfully completed."
# #             create_notification(request, application.user.id, 2, content)
# #             return JsonResponse({"message":"Application status changed to Completed"})
# #         else:
# #             application.status = 4
# #             content = "Your application has been approved. Awaiting placement"
# #             create_notification(request, application.user.id, 2, content)
# #             return JsonResponse({"message":"Application status changed to Awaiting placement"})





# class ChangeEmployerApplicationStatus(LoginRequiredMixin,View):
#     login_url = "account:login"
#     redirect_field_name = "redirect_to"
#     def get(self, request, id):
#         is_ajax = request.headers.get("X-Requested-With") == "XMLHttpRequest"
#         if is_ajax:
#             application = EmployerApplication.objects.get(id=id)
#             if application.status == 4:
#                 application.status = 3
#                 content = "Your application has been successfully completed."
#                 create_notification(request, application.user.id, 2, content)
#                 return JsonResponse({"message":"Application status changed to Completed"})
#             else:
#                 application.status = 4
#                 content = "Your application has been approved. Awaiting placement"
#                 create_notification(request, application.user.id, 2, content)
#                 return JsonResponse({"message":"Application status changed to Awaiting placement"})
#         else:
#             return JsonResponse({"message":"Something went wrong"})

# class StudentApplicationDetailView(LoginRequiredMixin,View):
#     login_url = "account:login"
#     redirect_field_name = "redirect_to"
#     def get(self, request, id):
#         template_name='main/application/students/application_detail.html'
#         application = JobApplication.objects.get(id=id)
#         if application.status == 1:
#             application.status = 2

#         context = {
#             "application":application
#         }
#         return render(request, template_name, context)

# class EmployerApplicationDetailView(LoginRequiredMixin,View):
#     login_url = "account:login"
#     redirect_field_name = "redirect_to"
#     def get(self, request, id):
#         template_name='main/application/employers/application_detail.html'
#         application = EmployerApplication.objects.get(id=id)
#         if application.status == 1:
#             application.status = 2

#         context = {
#             "application":application
#         }
#         return render(request, template_name, context)

# # admin applications view
# class AdminJobApplicationView(LoginRequiredMixin,View):
#     login_url = "account:login"
#     redirect_field_name = "redirect_to"
#     # form_class = AdminJobApplicationForm
#     template_name = 'accounts/main/application/admin/index.html'
    
#     def get(self,request):
#         profile = UserProfile.objects.get(user_id=request.user.id)    
#         context = {
#             "title":"Applications",
#             "profile":profile ,
#             # 'form':self.form_class
#             }
#         return render(request, self.template_name, context)
    
#     def post(self,request):
#         # is_ajax = request.headers.get("X-Requested-With") == "XMLHttpRequest"
#         # if is_ajax:
#         form = self.form_class(request.POST, request.FILES)
#         if form.is_valid():
#             form.instance.created_by=request.user
#             form.instance.status=1
#             content = f"An application has been received from {request.user.email}"
#             create_notification(request=request, notification_type=3, content=content)
#             form.save()
#             return JsonResponse({"message":"success"})
#         return JsonResponse({"message":form.errors})
 
# class AdminJobApplicationTableView(LoginRequiredMixin,View):
    
#     login_url = "accounts:login"
#     redirect_field_name = "redirect_to"

#     def get(self, request,  *args,index, **kwargs):
#         template = loader.get_template("accounts/main/application/admin/all_student_applications_table.html") 
        
#         profile = UserProfile.objects.get(user_id=request.user.id) 

#         if index == 3:
#             # branches = Branch.objects.filter(business_id=self.request.user.business_id,business_type=self.request.user.business_type )
#             # # title = "All Branches" 
#             student_job_applications = JobApplication.objects.all()
#         elif index == 4:
            
#             print("hi")

#         context = { 
#             'applications': student_job_applications,
#             "profile":profile ,
#             "index":index
#         }
#         return HttpResponse(template.render(context, self.request))

# class EmployerJobApplicationStaffView(LoginRequiredMixin, View):
#     login_url = "accounts:login"
#     redirect_field_name = "redirect_to"

#     def get(self, request,  *args, **kwargs):
#         template = loader.get_template("accounts/main/application/admin/employers/index.html")
#         profile = UserProfile.objects.get(user_id=request.user.id) 
#         # employer_job_applications = EmployerApplication.objects.all()
#         context = { 
#             'title': "Employer Applications",
#             'profile':profile,
#             # 'employee_applications': employer_job_applications
#         }
#         return HttpResponse(template.render(context, self.request))

# class EmployerJobApplicationStaffTableView(LoginRequiredMixin,View):
#     login_url = "accounts:login"
#     redirect_field_name = "redirect_to"

#     def get(self, request,  *args, **kwargs):
#         template = loader.get_template("accounts/main/application/admin/employers/table.html") 
#         employer_job_applications = EmployerApplication.objects.filter(user=request.user)
#         profile = UserProfile.objects.get(user_id=request.user.id) 
#         context = { 
#             'employer_job_applications': employer_job_applications,
#             "profile":profile ,
#         }
#         return HttpResponse(template.render(context, self.request))








# #Employers
# # class EmployerJobApplicationView(LoginRequiredMixin,View):
# #     login_url = "account:login"
# #     redirect_field_name = "redirect_to"
# #     form_class = EmployerJobApplicationForm
# #     template_name = 'accounts/main/application/employers/index.html'
    
# #     def get(self,request): 
# #         profile = UserProfile.objects.get(user_id=request.user.id)  
# #         context = {
# #             "title":"Employer Applications",
# #             'form':self.form_class, 
# #             'profile':profile
# #         }

templates/accounts/main/application/employerssss/index.html
{% extends 'accounts/main/base.html' %}
{% load static %}
{% block title %}{{ title }}{% endblock title %}</title>
{% block content %}
{% block styless %} 
<link rel="stylesheet" type="text/css" href="{% static 'main/assets/node_modules/datatables.net-bs4/css/dataTables.bootstrap4.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'main/assets/node_modules/datatables.net-bs4/css/responsive.dataTables.min.css' %}">{% endblock styless %}
<div class="container-fluid">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    {% include 'accounts/main/partials/bread_crumb.html' %}
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-10">
                            <h4 class="card-title">
                                <h6 class="card-title">Export data to Copy, CSV, Excel, PDF & Print</h6>
                            </h4>
                        </div>
                        <div class="col-sm-2"> 
                            <button
                            type="button"
                            class="btn btn-info float-right text-white"
                            data-bs-toggle="modal" data-bs-target="#exampleModal" data-whatever="@mdo"
                            >
                            <i class="fa fa-plus-circle"></i> Create New
                            </button> 
                        </div><br/>
                    </div>
                    <div class="m-t-40 table-responsive" data-href="{% url 'employers:get-job-application-table' %}">
                       
                    </div>
                </div>
            </div>   
        </div>
    </div>
</div>
<div class="modal" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel1">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="exampleModalLabel1">Job Description</h4>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"><span aria-hidden="true"></span></button>
            </div>
            <div class="modal-body">
                <form action="" method="post" id="formAddNew">
                    {% csrf_token %}
                    <div class="form-group">
                        <input class="form-control" placeholder="Job Title" name="title" id="message-text1"> 
                    </div> 
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <select class="form-control form-select" data-placeholder="Choose a Category" tabindex="1" name="related_field">
                                    <option value="">--Industry--</option>
                                    <option value="information technology">Information Technology</option>
                                    <option value="networking">Networking</option>
                                    <option value="fashion">Fashion</option>
                                    <option value="hardware">Hardware</option>
                                    <option value="graphic design">Graphic Design</option>
                                </select>
                            </div> 
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <select class="form-control form-select" tabindex="1" name="job_type">
                                    <option value="">--Job Type--</option> 
                                    <option value="1">Full-time</option>
                                    <option value="2">Part-time</option>
                                    <option value="3">Internship</option> 
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <input class="form-control" name="location" placeholder="Location" id="message-text1">  
                            </div> 
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <select class="form-control form-select" tabindex="1" name="highest_qualification">
                                    <option value="information technology">--Employment Type--</option> 
                                    <option value="remote">Remote</option>
                                    <option value="on_site">On site</option>
                                    <option value="hybrid">Hybrid</option>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <input class="form-control" placeholder="Budget" name="payment_budget" id="message-text1"> 
                            </div> 
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <select class="form-control form-select" tabindex="1" name="highest_qualification">
                                    <option value="information technology">--Years of Experience--</option> 
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option> 
                                    <option value="4">4</option> 
                                    <option value="5">5+</option> 
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <select class="form-control form-select" tabindex="1" name="highest_qualification">
                            <option value="information technology">--Qualification--</option> 
                            <option value="hnd">WASSCE</option>
                            <option value="degree">HND</option>
                            <option value="masters">Diploma</option> 
                            <option value="wassce">Bachelors degree</option> 
                            <option value="wassce">Masters degree</option> 
                            <option value="wassce">Doctorate degree</option> 
                        </select> 
                    </div>

                    <div class="form-group">
                        <textarea class="form-control" id="message-text1" rows="3" placeholder="Job Description" name="desciption"></textarea>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary text-white btnAddNew">Send message</button>
                    </div>
                </form>
            </div>
            
        </div>
    </div>
</div>

<div class="modal ViewMyAppModal" id="ViewMyAppModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel1" >
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="exampleModalLabel1"> </h4>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"><span aria-hidden="true"></span></button>
            </div>
            <div class="modal-body">
                <table class="table table-striped"> 
                    <tbody>
                        
                        <tr>
                            <td >Qualififaction</td> 
                            <td class="quli"></td> 
                        </tr> 
                        <tr>
                            <td>yrs of experience</td> 
                            <td class="exprie"></td> 
                        </tr> 
                        <tr>
                            <td>Payment Budget</td> 
                            <td class="payment_budget"></td> 
                        </tr> 
                        <tr>
                            <td>Location</td> 
                            <td class="location"></td> 
                        </tr> <tr>
                            <td>Desciption</td> 
                            <td  class="desciption"> </td> 
                        </tr> <tr>
                            <td>Created At</td> 
                            <td class="created_at"></td> 
                        </tr> 
                    </tbody>
                </table>
            </div> 
        </div>
    </div>
</div>



{% endblock content %}

{% block scripts %}
    
    <script src="{% static 'main/assets/node_modules/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'main/assets/node_modules/datatables.net-bs4/js/dataTables.responsive.min.js' %}"></script>

    <script src="https://cdn.datatables.net/buttons/1.5.1/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.print.min.js"></script>
    <!-- end - This is for export functionality only -->
    

    <script src="{% static 'main/dist/js/pages/custom/employer/application/index.js' %}"></script>
    {% comment %} <script src="{% static 'main/dist/js/pages/custom/employer_application.js' %}"></script> {% endcomment %}
{% endblock scripts %}

 

templates/accounts/main/application/employerssss/table.html
{% load static %}
<table id="example23"  class="display nowrap table table-hover table-striped border" cellspacing="0" width="100%">
    <thead>
        <tr  class="record">
            <th>Job Title</th>  
            <th hidden>qualification</th>
            <th hidden>yrs_of_experience</th>
            <th hidden>Payment Budget</th>
            <th hidden >Location</th>
            <th hidden >Desciption</th>
            <th hidden >Created at</th>
            <th>status</th>
            <th>Action</th>
        </tr>
    </thead> 
    <tbody >
        {%for application in employers_job_applications %}
        <tr class="record">
            <td>{{application.title }}</td>  
            <td hidden >{{application.highest_qualification }}</td>  
            <td hidden >{{application.yrs_of_experience }}</td>  
            <td hidden >{{application.payment_budget }}</td>  
            <td hidden >{{application.location }}</td>  
            <td hidden >{{application.desciption }}</td>  
            <td hidden >{{application.created_at }}</td>  
            <td><span class="label label-success"> {{application.get_status_display}}</span></td> 
            <td> 
                <a    class="ViewMyAppModalBtn"   id="app" app-data="{{ employers_job_applications }}"> <span class="label label-success"><i class="fa fa-eye"></i></span> </a>
                <a  class="btn_delete" href="{% url 'employers:employer-job-application-delete' application.id  %}"> <span class="label label-danger"><i class="fa fa-trash"></i></span> </a>
            </td>
        </tr> 
        {%endfor%}
    </tbody>
</table> 

<script>
    $(function () {
        $('#myTable').DataTable();
        
        // Order by the grouping
        $('#example tbody').on('click', 'tr.group', function () {
            var currentOrder = table.order()[0];
            if (currentOrder[0] === 2 && currentOrder[1] === 'asc') {
                table.order([2, 'desc']).draw();
            } else {
                table.order([2, 'asc']).draw();
            }
        });
        // responsive table
        $('#config-table').DataTable({
            responsive: true
        });
        $('#example23').DataTable({
            dom: 'Bfrtip',
            buttons: [
                'copy', 'csv', 'excel', 'pdf', 'print' 
            ]
        });
        $('.buttons-copy, .buttons-csv, .buttons-print, .buttons-pdf, .buttons-excel').addClass('btn btn-primary me-1 ');
    });

</script>
<script src="{% static 'main/dist/js/pages/custom/employer/application/table.js' %}"></script> 